### ISSUE TITLE
Integration Not appear in home assistant 

### ISSUE THREAD

**Issue by smunos66** [dotvav/vihio#4]
Hello, 

I want to try this integration but i can’t find it in home assistant. The Link « add integration to my HA » on this page https://www.home-assistant.io/integrations/palazzetti/ is Not working.

Thanks

**Comment by dotvav** [comment]
Have you installed Home Assistant 2024.11?

**Comment by smunos66** [comment]
Yes

core 2024.11.1
Supervisor 2024.11.2

When i try with the link i have this answer :
<img width="559" alt="image" src="https://github.com/user-attachments/assets/cfb664cc-a4b0-4484-926f-30a4b1bb696a">

**Comment by dotvav** [comment]
@smunos66 This is very strange. The link is working for me. One thought: do you have severali instances of Home Assistant running and are you sure that the link is sending you to the same Home Assistant instance as the one you have upgraded to 2024.11? Can you try other [new integrations in 2024.11](https://www.home-assistant.io/blog/2024/11/06/release-202411/#new-integrations)?

Now, this repo is not the right place to obtain support for Home Assistant. I suggest that you ask on [the Discord server](https://discord.gg/srh3NNkY), and if a Github issue is required to create it in [the Home Assistant repo](https://github.com/home-assistant/core/issues). If it is an issue with my integration it will be assigned to me.

**Comment by dotvav** [comment]
NB: I've also got [another Discord server](https://discord.gg/YSKvDNK2) for the discussions on the Home Assistant - Palazzetti integration (with a French channel).

I will now close this issue as it doesn't belong in this Github repo.
